/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group (THG).                                       *
 * All rights reserved.                                                    *
 *                                                                         *
 * This file is part of HDF5.  The full HDF5 copyright notice, including   *
 * terms governing use, modification, and redistribution, is contained in  *
 * the files COPYING and Copyright.html.  COPYING can be found at the root *
 * of the source code distribution tree; Copyright.html can be found at the*
 * root level of an installed copy of the electronic HDF5 document set and *
 * is linked from the top-level documents page.  It can also be found at   *
 * http://www.hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have    *
 * access to either file, you may request a copy from help@hdfgroup.org.   *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
//This file is automatically generated - do not directly modify.
#include "HDFException.h"

#include "HDFExceptionSubclasses.h"

namespace HDF5DotNet
{ 
   H5DcreateException::H5DcreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DopenException::H5DopenException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DcloseException::H5DcloseException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DreadException::H5DreadException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DwriteException::H5DwriteException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetSpaceException::H5DgetSpaceException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5DgetTypeException::H5DgetTypeException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5FcreateException::H5FcreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5FcloseException::H5FcloseException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5FopenException::H5FopenException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GcreateException::H5GcreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GopenException::H5GopenException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetObjInfoException::H5GgetObjInfoException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GIterateException::H5GIterateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GcloseException::H5GcloseException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScreateSimpleException::H5ScreateSimpleException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScreateException::H5ScreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentNdimsException::H5SgetSimpleExtentNdimsException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentDimsException::H5SgetSimpleExtentDimsException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5ScloseException::H5ScloseException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcopyException::H5TcopyException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TsetSizeException::H5TsetSizeException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcloseException::H5TcloseException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetSizeException::H5TgetSizeException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TsetOrderException::H5TsetOrderException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TopenException::H5TopenException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TinsertException::H5TinsertException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumCreateException::H5TenumCreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TenumInsertException::H5TenumInsertException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNativeTypeException::H5TgetNativeTypeException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TvlenCreateException::H5TvlenCreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetClassException::H5TgetClassException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetSignException::H5TgetSignException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNmembersException::H5TgetNmembersException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberNameException::H5TgetMemberNameException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberClassException::H5TgetMemberClassException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberIndexException::H5TgetMemberIndexException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetMemberTypeException::H5TgetMemberTypeException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcreateException::H5TcreateException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TgetNMembersException::H5TgetNMembersException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectStridedHyperslabException::H5SselectStridedHyperslabException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectHyperslabException::H5SselectHyperslabException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentMaxDimsException::H5SgetSimpleExtentMaxDimsException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SgetSimpleExtentNDimsException::H5SgetSimpleExtentNDimsException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5SselectNoneException::H5SselectNoneException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetNumObjectsException::H5GgetNumObjectsException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5GgetObjectNameByIndexException::H5GgetObjectNameByIndexException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5EsuppressPrintingException::H5EsuppressPrintingException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

   H5TcommitException::H5TcommitException(String^ message,
                                         unsigned int errorCode) : 
      HDFException(message, errorCode)
   {
   }

} // close namespace
