/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group (THG).                                       *
 * All rights reserved.                                                    *
 *                                                                         *
 * This file is part of HDF5.  The full HDF5 copyright notice, including   *
 * terms governing use, modification, and redistribution, is contained in  *
 * the files COPYING and Copyright.html.  COPYING can be found at the root *
 * of the source code distribution tree; Copyright.html can be found at the*
 * root level of an installed copy of the electronic HDF5 document set and *
 * is linked from the top-level documents page.  It can also be found at   *
 * http://www.hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have    *
 * access to either file, you may request a copy from help@hdfgroup.org.   *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
// This file is automatically generated - do not directly modify.
#pragma once
#include "HDFException.h"
namespace HDF5DotNet
{ 
   public ref class H5DcreateException : public HDFException
   {
     internal:
        H5DcreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5DopenException : public HDFException
   {
     internal:
        H5DopenException(String^ message, unsigned int errorCode);
   };

   public ref class H5DcloseException : public HDFException
   {
     internal:
        H5DcloseException(String^ message, unsigned int errorCode);
   };

   public ref class H5DreadException : public HDFException
   {
     internal:
        H5DreadException(String^ message, unsigned int errorCode);
   };

   public ref class H5DwriteException : public HDFException
   {
     internal:
        H5DwriteException(String^ message, unsigned int errorCode);
   };

   public ref class H5DgetSpaceException : public HDFException
   {
     internal:
        H5DgetSpaceException(String^ message, unsigned int errorCode);
   };

   public ref class H5DgetTypeException : public HDFException
   {
     internal:
        H5DgetTypeException(String^ message, unsigned int errorCode);
   };

   public ref class H5FcreateException : public HDFException
   {
     internal:
        H5FcreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5FcloseException : public HDFException
   {
     internal:
        H5FcloseException(String^ message, unsigned int errorCode);
   };

   public ref class H5FopenException : public HDFException
   {
     internal:
        H5FopenException(String^ message, unsigned int errorCode);
   };

   public ref class H5GcreateException : public HDFException
   {
     internal:
        H5GcreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5GopenException : public HDFException
   {
     internal:
        H5GopenException(String^ message, unsigned int errorCode);
   };

   public ref class H5GgetObjInfoException : public HDFException
   {
     internal:
        H5GgetObjInfoException(String^ message, unsigned int errorCode);
   };

   public ref class H5GIterateException : public HDFException
   {
     internal:
        H5GIterateException(String^ message, unsigned int errorCode);
   };

   public ref class H5GcloseException : public HDFException
   {
     internal:
        H5GcloseException(String^ message, unsigned int errorCode);
   };

   public ref class H5ScreateSimpleException : public HDFException
   {
     internal:
        H5ScreateSimpleException(String^ message, unsigned int errorCode);
   };

   public ref class H5ScreateException : public HDFException
   {
     internal:
        H5ScreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5SgetSimpleExtentNdimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentNdimsException(String^ message, unsigned int errorCode);
   };

   public ref class H5SgetSimpleExtentDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentDimsException(String^ message, unsigned int errorCode);
   };

   public ref class H5ScloseException : public HDFException
   {
     internal:
        H5ScloseException(String^ message, unsigned int errorCode);
   };

   public ref class H5TcopyException : public HDFException
   {
     internal:
        H5TcopyException(String^ message, unsigned int errorCode);
   };

   public ref class H5TsetSizeException : public HDFException
   {
     internal:
        H5TsetSizeException(String^ message, unsigned int errorCode);
   };

   public ref class H5TcloseException : public HDFException
   {
     internal:
        H5TcloseException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetSizeException : public HDFException
   {
     internal:
        H5TgetSizeException(String^ message, unsigned int errorCode);
   };

   public ref class H5TsetOrderException : public HDFException
   {
     internal:
        H5TsetOrderException(String^ message, unsigned int errorCode);
   };

   public ref class H5TopenException : public HDFException
   {
     internal:
        H5TopenException(String^ message, unsigned int errorCode);
   };

   public ref class H5TinsertException : public HDFException
   {
     internal:
        H5TinsertException(String^ message, unsigned int errorCode);
   };

   public ref class H5TenumCreateException : public HDFException
   {
     internal:
        H5TenumCreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5TenumInsertException : public HDFException
   {
     internal:
        H5TenumInsertException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetNativeTypeException : public HDFException
   {
     internal:
        H5TgetNativeTypeException(String^ message, unsigned int errorCode);
   };

   public ref class H5TvlenCreateException : public HDFException
   {
     internal:
        H5TvlenCreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetClassException : public HDFException
   {
     internal:
        H5TgetClassException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetSignException : public HDFException
   {
     internal:
        H5TgetSignException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetNmembersException : public HDFException
   {
     internal:
        H5TgetNmembersException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetMemberNameException : public HDFException
   {
     internal:
        H5TgetMemberNameException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetMemberClassException : public HDFException
   {
     internal:
        H5TgetMemberClassException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetMemberIndexException : public HDFException
   {
     internal:
        H5TgetMemberIndexException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetMemberTypeException : public HDFException
   {
     internal:
        H5TgetMemberTypeException(String^ message, unsigned int errorCode);
   };

   public ref class H5TcreateException : public HDFException
   {
     internal:
        H5TcreateException(String^ message, unsigned int errorCode);
   };

   public ref class H5TgetNMembersException : public HDFException
   {
     internal:
        H5TgetNMembersException(String^ message, unsigned int errorCode);
   };

   public ref class H5SselectStridedHyperslabException : public HDFException
   {
     internal:
        H5SselectStridedHyperslabException(String^ message, unsigned int errorCode);
   };

   public ref class H5SselectHyperslabException : public HDFException
   {
     internal:
        H5SselectHyperslabException(String^ message, unsigned int errorCode);
   };

   public ref class H5SgetSimpleExtentMaxDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentMaxDimsException(String^ message, unsigned int errorCode);
   };

   public ref class H5SgetSimpleExtentNDimsException : public HDFException
   {
     internal:
        H5SgetSimpleExtentNDimsException(String^ message, unsigned int errorCode);
   };

   public ref class H5SselectNoneException : public HDFException
   {
     internal:
        H5SselectNoneException(String^ message, unsigned int errorCode);
   };

   public ref class H5GgetNumObjectsException : public HDFException
   {
     internal:
        H5GgetNumObjectsException(String^ message, unsigned int errorCode);
   };

   public ref class H5GgetObjectNameByIndexException : public HDFException
   {
     internal:
        H5GgetObjectNameByIndexException(String^ message, unsigned int errorCode);
   };

   public ref class H5EsuppressPrintingException : public HDFException
   {
     internal:
        H5EsuppressPrintingException(String^ message, unsigned int errorCode);
   };

   public ref class H5TcommitException : public HDFException
   {
     internal:
        H5TcommitException(String^ message, unsigned int errorCode);
   };

} // close namespace
