using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DataStructures
{
    /// <summary>
    /// This class is used to save a snapshot of a the digital and analog
    /// buffers generated by a particular sequence and settings file, for testing purposes.
    /// </summary>
    [Serializable]
    public class BufferTestSnapshot
    {
        private SequenceData sequence;

        public SequenceData Sequence
        {
            get { return sequence; }
            set { sequence = value; }
        }

        private SettingsData settings;

        public SettingsData Settings
        {
            get { return settings; }
            set { settings = value; }
        }

        private double masterTimebaseSampleDuration;

        public double MasterTimebaseSampleDuration
        {
            get { return masterTimebaseSampleDuration; }
            set { masterTimebaseSampleDuration = value; }
        }

        private Dictionary<int, bool[]> digitalFixed;

        public Dictionary<int, bool[]> DigitalFixed
        {
            get { return digitalFixed; }
            set { digitalFixed = value; }
        }


        private Dictionary<int, bool[]> digitalVar;

        public Dictionary<int, bool[]> DigitalVar
        {
            get { return digitalVar; }
            set { digitalVar = value; }
        }


        private Dictionary<int, double[]> analogFixed;

        public Dictionary<int, double[]> AnalogFixed
        {
            get { return analogFixed; }
            set { analogFixed = value; }
        }


        private Dictionary<int, double[]> analogVar;

        public Dictionary<int, double[]> AnalogVar
        {
            get { return analogVar; }
            set { analogVar = value; }
        }
    }
}
